/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service Info */
        get: operations["service_info__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_v1_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_api_v1_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_api_v1_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/packet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Packet */
        put: operations["update_packet_api_v1_conversations__conversation_id__packet_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/turns/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream Turn */
        post: operations["stream_turn_api_v1_conversations__conversation_id__turns_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foundation/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream Foundation Chat */
        post: operations["stream_foundation_chat_api_v1_foundation_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConversationDetail */
        ConversationDetail: {
            conversation: components["schemas"]["ConversationView"];
            /** Messages */
            messages: components["schemas"]["MessageView"][];
            packet: components["schemas"]["PacketView"] | null;
            /** Runs */
            runs: components["schemas"]["RunView"][];
        };
        /** ConversationView */
        ConversationView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Organization Id */
            organization_id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CreateConversationRequest */
        CreateConversationRequest: {
            /**
             * Title
             * @default New planning conversation
             */
            title: string;
        };
        /** DoneEvent */
        DoneEvent: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Cursor */
            cursor: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "done";
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "failed" | "cancelled";
        };
        /** ErrorEvent */
        ErrorEvent: {
            /** Code */
            code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Cursor */
            cursor: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "error";
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
        };
        /** FoundationChatRequest */
        FoundationChatRequest: {
            /**
             * After Cursor
             * @default -1
             */
            after_cursor: number;
            /** Client Message Id */
            client_message_id: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MessageView */
        MessageView: {
            /** Content */
            content: string;
            /** Conversation Id */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Run Id */
            run_id: string | null;
        };
        /** PacketUpdateRequest */
        PacketUpdateRequest: {
            /** Base Version */
            base_version: number;
            /** Content */
            content: {
                [key: string]: unknown;
            };
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** PacketView */
        PacketView: {
            /** Content */
            content: {
                [key: string]: unknown;
            };
            /** Conversation Id */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Version */
            version: number;
        };
        /** RunView */
        RunView: {
            /** Completed At */
            completed_at: string | null;
            /** Conversation Id */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Retry Of */
            retry_of: string | null;
            /**
             * Runtime
             * @enum {string}
             */
            runtime: "fixture" | "provider";
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "completed" | "failed" | "cancelled";
        };
        /** SessionEvent */
        SessionEvent: {
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Cursor */
            cursor: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "session";
            /** Run Id */
            run_id: string;
            /**
             * Runtime
             * @default fixture
             * @enum {string}
             */
            runtime: "fixture" | "provider";
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
        };
        /** StatusEvent */
        StatusEvent: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Cursor */
            cursor: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "status";
            /** Message Id */
            message_id?: string | null;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "completed" | "failed" | "cancelled";
        };
        /** TextDeltaEvent */
        TextDeltaEvent: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Cursor */
            cursor: number;
            /** Delta */
            delta: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "text_delta";
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
        };
        /** TurnStreamRequest */
        TurnStreamRequest: {
            /**
             * After Cursor
             * @default -1
             */
            after_cursor: number;
            /** Client Message Id */
            client_message_id: string;
            /** Message */
            message: string;
            /** Reconnect Run Id */
            reconnect_run_id?: string | null;
            /** Retry Of */
            retry_of?: string | null;
            /**
             * Runtime
             * @default fixture
             * @enum {string}
             */
            runtime: "fixture" | "provider";
        };
        /** UsageEvent */
        UsageEvent: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Cursor */
            cursor: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "usage";
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            usage: components["schemas"]["UsageSnapshot"];
        };
        /** UsageSnapshot */
        UsageSnapshot: {
            /**
             * Actual Service Tier
             * @default fixture
             */
            actual_service_tier: string;
            /** Cache Write Tokens */
            cache_write_tokens: number;
            /** Cached Input Tokens */
            cached_input_tokens: number;
            /**
             * Cost Microusd
             * @default 0
             */
            cost_microusd: number;
            /**
             * Evidence Class
             * @enum {string}
             */
            evidence_class: "synthetic" | "development";
            /** Input Tokens */
            input_tokens: number;
            /** Model */
            model: string;
            /** Output Tokens */
            output_tokens: number;
            /**
             * Price Version
             * @default synthetic-zero-v1
             */
            price_version: string;
            /** Provider */
            provider: string;
            /** Reasoning Tokens */
            reasoning_tokens: number;
            /** Total Tokens */
            total_tokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    service_info__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_conversations_api_v1_conversations_get: {
        parameters: {
            query?: never;
            header?: {
                "x-clio-organization"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_v1_conversations_post: {
        parameters: {
            query?: never;
            header?: {
                "x-clio-organization"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_v1_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-clio-organization"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_packet_api_v1_conversations__conversation_id__packet_put: {
        parameters: {
            query?: never;
            header?: {
                "x-clio-organization"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PacketUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PacketView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_turn_api_v1_conversations__conversation_id__turns_stream_post: {
        parameters: {
            query?: never;
            header?: {
                "x-clio-organization"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnStreamRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEvent"] | components["schemas"]["StatusEvent"] | components["schemas"]["TextDeltaEvent"] | components["schemas"]["UsageEvent"] | components["schemas"]["ErrorEvent"] | components["schemas"]["DoneEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_foundation_chat_api_v1_foundation_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoundationChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEvent"] | components["schemas"]["StatusEvent"] | components["schemas"]["TextDeltaEvent"] | components["schemas"]["UsageEvent"] | components["schemas"]["ErrorEvent"] | components["schemas"]["DoneEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "x-clio-organization"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
